### ISSUE TITLE
`message.content` deprecation

### ISSUE THREAD

**Issue by shadowplay1** [Munz1211-Project/DISCORD-JS-V13-TEMPLATE#12]
`message.content` and commands like `!help` wont be available for verified bots from April, 2021. read this:
https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-for-Verified-Bots

so i highly suggest you to rewrite the bot for slash commands

here's the discord's interaction api docs:
https://discord.com/developers/docs/interactions/application-commands

**Comment by Munz1211** [comment]
I know but I'm not going to slash command because it's bad. but I made this not for that purpose, the real purpose is just for learning

**Comment by KagChi** [comment]
> `message.content` and commands like `!help` wont be available for verified bots from April, 2021. read this: https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-for-Verified-Bots
> 
> so i highly suggest you to rewrite the bot for slash commands
> 
> here's the discord's interaction api docs: https://discord.com/developers/docs/interactions/application-commands

and? is this repository for verified bots? What is the relation?
