### ISSUE TITLE
.env issue

### ISSUE THREAD

**Issue by SpreeHertz** [Munz1211-Project/DISCORD-JS-V13-TEMPLATE#14]
# dotenv

In [server.js](https://github.com/Munz1211-Project/DISCORD-JS-V13-TEMPLATE/blob/main/server.js), you've done `process.env.PORT`. This won't work since you haven't required the `dotenv` package nor is there a `.env` or `.env.example` found in the repo nor specified in the Readme.

**Comment by KagChi** [comment]
No, even you dont use dotenv, you still can get PORT environment, except you editing the port using .env file

**Comment by SpreeHertz** [comment]
Sorry for the inconvenience. I didn't know that.
